################################################################################
#                                                                              #
# Project:      IPK25 Chat Client                                              #
# University:   Faculty of Information Technology, BUT                         #
# Subject:      IPK: Computer Communications and Networks                      #
#                                                                              #
# File:         Server.py                                                      #
# Author:       Jan Kalina <xkalinj00>                                         #
#               !!! by GitHub Copilot's Claude 3.7 Sonnet Thinking model !!!   #
#                                                                              #
# Created:      18.04.2025                                                     #
# Last edit:    20.04.2025                                                     #
#                                                                              #
# Description:  A testing server implementation for IPK25 Chat Client that     #
#               provides local testing environment. This server allows testing #
#               of the IPK25 Chat Client application by implementing the       #
#               required server communication protocol.                        #
#                                                                              #
################################################################################
#                                                                              #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ DISCLAIMER ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# This file was almost entirely AI-generated by the Claude 3.7 Sonnet Thinking #
# model of GitHub Copilot. The author does not claim authorship of this code   #
# and requests that it not be evaluated as part of the project submission or   #
# used as a basis for plagiarism detection. This is strictly an auxiliary      #
# Python script intended to facilitate local testing of the IPK25 Chat Client  #
# using a localhost server implementation.                                     #
#                                                                              #
################################################################################

import socket
import threading
import signal
import sys
import re
import queue
import select
import struct
import time

HOST = "127.0.0.1"
PORT = 4567

MSG_TYPE_UNKNOWN = 0xAA
MSG_TYPE_CONFIRM = 0x00
MSG_TYPE_REPLY = 0x01
MSG_TYPE_AUTH = 0x02
MSG_TYPE_JOIN = 0x03
MSG_TYPE_MSG = 0x04
MSG_TYPE_PING = 0xFD
MSG_TYPE_ERR = 0xFE
MSG_TYPE_BYE = 0xFF

MSG_TYPE_NAMES = {
        0x00: "CONFIRM",
        0x01: "REPLY",
        0x02: "AUTH",
        0x03: "JOIN",
        0x04: "MSG",
        0xFD: "PING",
        0xFE: "ERR",
        0xFF: "BYE",
        0xAA: "UNKNOWN"
        }

def handle_auth(srv, sender, uname, dname, secret):
    protocol_type = "UDP" if sender.protocol == "udp" else "TCP"
    print(f"AUTH ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): AUTH {uname} USING *** AS {dname}")

    sender.display_name = dname

    join_msg = f"User {sender.display_name} has joined the channel"
    for client in srv.clients:
        if client != sender and client.active and client.channel == sender.channel:
            client.send_msg("System", join_msg)

    sender.send_reply(True, f"Welcome! You are now in channel {sender.channel}")

def handle_join(srv, sender, channel_id, display_name=None):
    old_channel = sender.channel
    protocol_type = "UDP" if sender.protocol == "udp" else "TCP"

    if display_name:
        sender.display_name = display_name

    print(f"JOIN ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): JOIN {channel_id} AS {sender.display_name}")

    if sender.display_name and old_channel != channel_id:
        leave_msg = f"User {sender.display_name} has left the channel"
        for client in srv.clients:
            if client != sender and client.active and client.channel == old_channel:
                client.send_msg("System", leave_msg)

    if channel_id not in srv.channels:
        srv.channels.append(channel_id)

    sender.channel = channel_id
    sender.send_reply(True, f"Joined channel {channel_id}")

    if sender.display_name:
        join_msg = f"User {sender.display_name} has joined the channel"
        for client in srv.clients:
            if client != sender and client.active and client.channel == channel_id:
                client.send_msg("System", join_msg)

def handle_msg(srv, sender, dname, content):
    protocol_type = "UDP" if sender.protocol == "udp" else "TCP"
    print(f"MSG ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): MSG FROM {dname} IS {content}")

    for client in srv.clients:
        if client.active and (sender.channel == client.channel) and (client != sender):
            client.send_msg(dname, content)

def handle_err(srv, sender, dname, content):
    protocol_type = "UDP" if sender.protocol == "udp" else "TCP"
    print(f"ERR ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): ERR FROM {dname} IS {content}")
    sender.close()

def handle_bye(srv, sender, dname):
    protocol_type = "UDP" if sender.protocol == "udp" else "TCP"
    print(f"BYE ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): BYE FROM {dname}")

    if sender.channel and sender.display_name:
        system_msg = f"User {sender.display_name} has left the channel"
        for client in srv.clients:
            if client != sender and client.active and client.channel == sender.channel:
                client.send_msg("System", system_msg)

    sender.close()

patterns = {
    "AUTH": re.compile(r"^AUTH ([a-zA-Z0-9_\-]+) AS ([a-zA-Z0-9_\-]+) USING ([a-zA-Z0-9_\-]+)\r\n$"),
    "JOIN": re.compile(r"^JOIN ([a-zA-Z0-9_\-]+) AS ([a-zA-Z0-9_\-]+)\r\n$"),
    "MSG": re.compile(r"^MSG FROM ([\x21-\x7E]+) IS ([\x20-\x7E\x0A]+)\r\n$"),
    "ERR": re.compile(r"^ERR FROM ([\x21-\x7E]+) IS ([\x20-\x7E\x0A]+)\r\n$"),
    "BYE": re.compile(r"^BYE FROM ([\x21-\x7E]+)\r\n$"),
    }

handlers = {
    "AUTH": handle_auth,
    "JOIN": lambda srv, sender, channel_id, display_name: handle_join(srv, sender, channel_id, display_name),
    "MSG": handle_msg,
    "ERR": handle_err,
    "BYE": handle_bye
    }

class Client:
    def __init__(self, server, protocol, socket_or_addr, def_channel):
        self.server = server
        self.protocol = protocol
        self.active = True
        self.channel = def_channel
        self.binary_mode = False
        self.last_msg_id = 0
        self.display_name = None

        if protocol == "tcp":
            self.skt = socket_or_addr
            self.addr = socket_or_addr.getpeername()
            self.thread = threading.Thread(target=self.handle_tcp)
            self.thread.start()
        else:
            self.skt = None
            self.addr = socket_or_addr

    def send_udp_binary_message(self, client, msg_type_byte, msg_id, payload=b''):
        if not client.active or client.protocol != "udp":
            return False

        protocol_type = "UDP"

        if msg_type_byte == MSG_TYPE_PING:
            print(f"SEND ({protocol_type}, '{client.addr[0]}', {client.addr[1]}): PING {msg_id} {msg_id:04X}")

        binary_msg = struct.pack('!BH', msg_type_byte, msg_id) + payload

        try:
            if msg_type_byte != MSG_TYPE_CONFIRM:
                self.track_udp_message(client.addr, msg_id, msg_type_byte)

            self.udp_socket.sendto(binary_msg, client.addr)
            return True
        except Exception as e:
            print(f"Error sending UDP message: {e}")
            return False

    def handle_tcp(self):
        try:
            while self.active:
                data = self.skt.recv(60200)
                if not data:
                    break

                self.server.handle_msg(self, data.decode('ascii'))
        except Exception as e:
            print(f"Error handling TCP client: {e}")
        finally:
            self.close()

    def close(self):
        if not self.active:
            return
        self.active = False

        if self.protocol == "tcp" and self.skt:
            try:
                self.skt.shutdown(socket.SHUT_RDWR)
                self.skt.close()
            except:
                pass

        if self in self.server.clients:
            self.server.clients.remove(self)

        if self.protocol == "udp" and self.addr in self.server.udp_clients:
            del self.server.udp_clients[self.addr]

    def send_reply(self, status: bool, message: str):
        protocol_type = "UDP" if self.protocol == "udp" else "TCP"
        s_msg = "OK" if status else "NOK"
        print(f"SEND ({protocol_type}, '{self.addr[0]}', {self.addr[1]}): REPLY {s_msg} IS {message}")

        if self.binary_mode and self.protocol == "udp":
            msg_id = self.server.get_next_msg_id()
            result_byte = 1 if status else 0

            payload = struct.pack('!B', result_byte) + \
                      struct.pack('!H', self.last_msg_id) + \
                      message.encode('utf-8') + b'\x00'

            self.server.send_udp_binary_message(self, MSG_TYPE_REPLY, msg_id, payload)
        else:
            msg = f"REPLY {s_msg} IS {message}\r\n".encode()
            try:
                if self.protocol == "tcp":
                    self.skt.send(msg)
                else:
                    self.server.udp_socket.sendto(msg, self.addr)
            except Exception as e:
                print(f"Error sending reply: {e}")
                self.close()

    def send_bye(self, display_name: str = "Server"):
        if not self.active:
            return

        protocol_type = "UDP" if self.protocol == "udp" else "TCP"
        print(f"SEND ({protocol_type}, '{self.addr[0]}', {self.addr[1]}): BYE FROM {display_name}")

        if self.binary_mode and self.protocol == "udp":
            msg_id = self.server.get_next_msg_id()
            payload = display_name.encode('utf-8') + b'\x00'
            self.server.send_udp_binary_message(self, MSG_TYPE_BYE, msg_id, payload)
        else:
            msg = f"BYE FROM {display_name}\r\n".encode()
            try:
                if self.protocol == "tcp":
                    self.skt.send(msg)
                else:
                    self.server.udp_socket.sendto(msg, self.addr)
            except Exception as e:
                print(f"Error sending BYE: {e}")

    def send_msg(self, display_name: str, content: str):
        protocol_type = "UDP" if self.protocol == "udp" else "TCP"

        if self.binary_mode and self.protocol == "udp":
            msg_id = self.server.get_next_msg_id()
            payload = display_name.encode('utf-8') + b'\x00' + content.encode('utf-8') + b'\x00'
            self.server.send_udp_binary_message(self, MSG_TYPE_MSG, msg_id, payload)
        else:
            msg = f"MSG FROM {display_name} IS {content}\r\n".encode()
            try:
                if self.protocol == "tcp":
                    self.skt.send(msg)
                else:
                    self.server.udp_socket.sendto(msg, self.addr)
            except Exception as e:
                print(f"Error sending message: {e}")
                self.close()

class User:
    def __init__(self, uname: str, secret: str):
        self.uname = uname
        self.secret = secret

class Server:
    def __init__(self, host: str, port: int):
        self.tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.tcp_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.tcp_socket.bind((host, port))
        self.tcp_socket.listen()

        self.udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.udp_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.udp_socket.bind((host, port))

        self.clients = []
        self.udp_clients = {}
        self.udp_pending_messages = {}
        self.def_channel = "default"
        self.channels = [self.def_channel]
        self.queue = queue.Queue()
        self.running = True
        self.next_msg_id = 1

        self.msgproc = threading.Thread(target=self.__msg_proc_routine)
        self.msgproc.start()

        self.ping_thread = threading.Thread(target=self.__ping_routine)
        self.ping_thread.daemon = True
        self.ping_thread.start()

    def get_msg_type_name(self, msg_type_byte):
        return MSG_TYPE_NAMES.get(msg_type_byte, f"UNKNOWN({msg_type_byte:02X})")


    def get_next_msg_id(self):
        msg_id = self.next_msg_id
        self.next_msg_id = (self.next_msg_id + 1) % 65536
        return msg_id

    def track_udp_message(self, client_addr, msg_id, msg_type):
        if client_addr not in self.udp_pending_messages:
            self.udp_pending_messages[client_addr] = {}

        self.udp_pending_messages[client_addr][msg_id] = {
                'sent_time': time.time(),
                'msg_type': msg_type,
                'responded': False
                }

    def parse_binary_message(self, data):
        if len(data) < 3:
            return None, None, None

        msg_type = data[0]

        msg_id = struct.unpack('!H', data[1:3])[0]

        if msg_type == MSG_TYPE_AUTH:
            fields = data[3:].split(b'\x00')
            if len(fields) >= 3:
                username = fields[0].decode('utf-8')
                display_name = fields[1].decode('utf-8')
                secret = fields[2].decode('utf-8')
                return "AUTH", msg_id, (username, display_name, secret)

        elif msg_type == MSG_TYPE_JOIN:
            fields = data[3:].split(b'\x00')
            if len(fields) >= 2:
                channel_id = fields[0].decode('utf-8')
                display_name = fields[1].decode('utf-8') if len(fields) > 1 else ""
                return "JOIN", msg_id, (channel_id, display_name)

        elif msg_type == MSG_TYPE_MSG:
            fields = data[3:].split(b'\x00')
            if len(fields) >= 2:
                display_name = fields[0].decode('utf-8')
                content = fields[1].decode('utf-8')
                return "MSG", msg_id, (display_name, content)

        elif msg_type == MSG_TYPE_BYE:
            fields = data[3:].split(b'\x00')
            if len(fields) >= 1:
                display_name = fields[0].decode('utf-8')
                return "BYE", msg_id, (display_name,)

        elif msg_type == MSG_TYPE_ERR:
            fields = data[3:].split(b'\x00')
            if len(fields) >= 2:
                display_name = fields[0].decode('utf-8')
                content = fields[1].decode('utf-8')
                return "ERR", msg_id, (display_name, content)

        elif msg_type == MSG_TYPE_PING:
            return "PING", msg_id, ()

        elif msg_type == MSG_TYPE_CONFIRM:
            ref_msg_id = struct.unpack('!H', data[1:3])[0]
            return "CONFIRM", ref_msg_id, ()

        return None, None, None

    def send_ping(self, client):
        if not client.active or client.protocol != "udp":
            return False

        msg_id = self.get_next_msg_id()
        return self.send_udp_binary_message(client, MSG_TYPE_PING, msg_id)

    def send_udp_binary_message(self, client, msg_type_byte, msg_id, payload=b''):
        if not client.active or client.protocol != "udp":
            return False

        protocol_type = "UDP"

        if msg_type_byte == MSG_TYPE_PING:
            print(f"SEND ({protocol_type}, '{client.addr[0]}', {client.addr[1]}): PING {msg_id}")

        binary_msg = struct.pack('!BH', msg_type_byte, msg_id) + payload

        try:
            if msg_type_byte != MSG_TYPE_CONFIRM:
                self.track_udp_message(client.addr, msg_id, msg_type_byte)

            self.udp_socket.sendto(binary_msg, client.addr)
            return True
        except Exception as e:
            print(f"Error sending UDP message: {e}")
            return False

    def send_confirm(self, client, msg_id):
        protocol_type = "UDP" if client.protocol == "udp" else "TCP"

        if client.binary_mode and client.protocol == "udp":
            self.send_udp_binary_message(client, MSG_TYPE_CONFIRM, msg_id)
            print(f"SEND ({protocol_type}, '{client.addr[0]}', {client.addr[1]}): CONFIRM {msg_id} ({msg_id:04X})")
        else:
            pass

    def __ping_routine(self):
        PING_INTERVAL = 60.0
        MESSAGE_TIMEOUT = 5.0

        while self.running:
            time.sleep(PING_INTERVAL)
            current_time = time.time()

            for client in [c for c in self.clients if c.protocol == "udp" and c.active]:
                self.send_ping(client)

            for addr in list(self.udp_pending_messages.keys()):
                messages = list(self.udp_pending_messages[addr].items())

                for msg_id, info in messages:
                    if not info['responded'] and (current_time - info['sent_time']) > MESSAGE_TIMEOUT:
                        if addr in self.udp_clients:
                            client = self.udp_clients[addr]
                            print(f"UDP client {addr} did not respond to message ID {msg_id}, disconnecting")
                            client.send_bye("Server")
                            client.close()

                            if addr in self.udp_pending_messages:
                                del self.udp_pending_messages[addr]
                            break

                    elif info['responded'] and (current_time - info['sent_time']) > MESSAGE_TIMEOUT:
                        del self.udp_pending_messages[addr][msg_id]

                if addr in self.udp_pending_messages and not self.udp_pending_messages[addr]:
                    del self.udp_pending_messages[addr]

    def handle_binary_message(self, client, msg_type, msg_id, args):
        client.last_msg_id = msg_id
        result = False

        if msg_type == "AUTH":
            if len(args) == 3:
                username, display_name, secret = args
                handle_auth(self, client, username, display_name, secret)
                result = True

        elif msg_type == "JOIN":
            if len(args) >= 1:
                channel_id = args[0]
                display_name = args[1] if len(args) > 1 else client.display_name
                handle_join(self, client, channel_id, display_name)
                result = True

        elif msg_type == "MSG":
            if len(args) == 2:
                display_name, content = args
                handle_msg(self, client, display_name, content)
                result = True

        elif msg_type == "BYE":
            if len(args) == 1:
                display_name = args[0]
                handle_bye(self, client, display_name)
                result = True

        elif msg_type == "ERR":
            if len(args) == 2:
                display_name, content = args
                handle_err(self, client, display_name, content)
                result = True

        elif msg_type == "PING":
            protocol_type = "UDP" if client.protocol == "udp" else "TCP"
            print(f"PING ({protocol_type}, '{client.addr[0]}', {client.addr[1]}): PING {msg_id}")
            result = True

        elif msg_type == "CONFIRM":
            if client.addr in self.udp_pending_messages and msg_id in self.udp_pending_messages[client.addr]:
                self.udp_pending_messages[client.addr][msg_id]['responded'] = True
                msg_type_byte = self.udp_pending_messages[client.addr][msg_id]['msg_type']
                msg_type_name = self.get_msg_type_name(msg_type_byte)
                protocol_type = "UDP"
                print(f"CONFIRM ({protocol_type}, '{client.addr[0]}', {client.addr[1]}): {msg_type_name} {msg_id} ({msg_id:04X}) confirmed")
            else:
                print(f"UNMATCHED CONFIRM from {client.addr[0]}:{client.addr[1]}: {msg_id} ({msg_id:04X})")
                if client.addr in self.udp_pending_messages:
                    print(f"Pending messages for this client: {list(self.udp_pending_messages[client.addr].keys())}")
            result = True

        return result

    def start(self):
        inputs = [self.tcp_socket, self.udp_socket]

        while self.running:
            try:
                readable, _, _ = select.select(inputs, [], [], 1.0)

                for sock in readable:
                    if sock is self.tcp_socket:
                        client_socket, client_address = self.tcp_socket.accept()
                        print(f"CONNECTION (TCP, '{client_address[0]}', {client_address[1]}): New client connected")
                        client = Client(self, "tcp", client_socket, self.def_channel)
                        self.clients.append(client)

                    elif sock is self.udp_socket:
                        data, addr = self.udp_socket.recvfrom(60200)

                        if addr not in self.udp_clients:
                            print(f"CONNECTION (UDP, '{addr[0]}', {addr[1]}): New client connected")
                            client = Client(self, "udp", addr, self.def_channel)
                            self.clients.append(client)
                            self.udp_clients[addr] = client

                        client = self.udp_clients[addr]
                        msg_type, msg_id, args = self.parse_binary_message(data)
                        if msg_type:
                            client.binary_mode = True

                            if msg_type != "CONFIRM":
                                self.send_confirm(client, msg_id)

                            self.handle_binary_message(client, msg_type, msg_id, args)
                        else:
                            try:
                                text_message = data.decode('ascii')
                                self.handle_msg(client, text_message)
                            except Exception as e:
                                print(f"UNRECOGNIZED (UDP, '{addr[0]}', {addr[1]}): {data}")

            except Exception as e:
                print(f"Server error: {e}")
                break

    def stop(self):
        print("Stopping server...")
        self.running = False

        for client in list(self.clients):
            try:
                client.send_bye("Server")
            except Exception as e:
                print(f"Error sending BYE message to client {client.addr}: {e}")
            finally:
                client.close()

        self.tcp_socket.close()
        self.udp_socket.close()

    def handle_msg(self, sender, msg: str):
        self.queue.put((sender, msg))

    def __proc_msg(self, sender, msg: str):
        for name, pattern in patterns.items():
            match = pattern.match(msg)
            if match:
                handlers[name](self, sender, *match.groups())
                return
        protocol_type = "UDP" if sender.protocol == "udp" else "TCP"
        print(f"UNRECOGNIZED ({protocol_type}, '{sender.addr[0]}', {sender.addr[1]}): {msg}")

    def __msg_proc_routine(self):
        while self.running:
            try:
                sender, message = self.queue.get(timeout=1.0)
                self.__proc_msg(sender, message)
            except queue.Empty:
                continue
            except Exception as e:
                print(f"Error processing message: {e}")

srv = Server(HOST, PORT)

def handler(sig, frame):
    print(f"Signal {sig} received, exiting...")
    srv.stop()
    sys.exit(0)

signal.signal(signal.SIGINT, handler)
signal.signal(signal.SIGTERM, handler)
srv.start()

### End of the file Server.py ###
