/*******************************************************************************
 *                                                                             *
 * Project:      IPK25 Chat Client                                             *
 * University:   Faculty of Information Technology, BUT                        *
 * Subject:      IPK: Computer Communications and Networks                     *
 *                                                                             *
 * File:         CommandLineOptions.hpp                                        *
 * Author:       Jan Kalina <xkalinj00>                                        *
 *                                                                             *
 * Created:      06.04.2025                                                    *
 * Last edit:    06.04.2025                                                    *
 *                                                                             *
 * Description:  This file contains the definition of the CommandLineOptions   *
 *               class, which is used for storing command line options for     *
 *               the IPK25 Chat Client application.                            *
 *                                                                             *
 ******************************************************************************/
/**
 * @file CommandLineOptions.hpp
 * @author Jan Kalina \<xkalinj00>
 * @brief Header file for the CommandLineOptions class.
 */

#ifndef COMMAND_LINE_OPTIONS_HPP
#define COMMAND_LINE_OPTIONS_HPP

#include "Enums/TransportProtocolTypes.hpp"
#include <string>   // std::string
#include <cstdint>  // uint8_t, uint16_t

namespace IPK25ChatClient::Common
{
    /**
     * @class CommandLineOptions
     * @brief A class for holding command line options for the IPK25 Chat Client.
     */
    class CommandLineOptions final {
    public:
        /**
         * @brief Default constructor for CommandLineOptions class.
         */
        explicit CommandLineOptions();

        Enums::TransportProtocol mTransportProtocol;  /**< Transport protocol type (TCP or UDP).  */
        std::string mServer;                          /**< Server IP address or hostname.         */
        uint16_t mServerPort;                         /**< Server port number.                    */
        uint8_t mUdpMaxRetransmit;                    /**< Maximum number of UDP retransmissions. */
        uint16_t mUdpTimeoutMs;                       /**< UDP timeout duration in milliseconds.  */

        /**
         * @brief Equality operator for CommandLineOptions class.
         *
         * @details This operator compares two CommandLineOptions objects for
         *          equality. It is automatically generated by the compiler
         *          and compares all member variables.
         *
         * @param other The other CommandLineOptions object to compare with.
         * @return True if all member variables are equal, False otherwise.
         */
        bool operator==(const CommandLineOptions &other) const = default;
    }; // CommandLineOptions
} // IPK25ChatClient::Common

#endif // COMMAND_LINE_OPTIONS_HPP

/*** end of file CommandLineOptions.hpp ***/
