/*******************************************************************************
 *                                                                             *
 * Project:      IPK25 Chat Client                                             *
 * University:   Faculty of Information Technology, BUT                        *
 * Subject:      IPK: Computer Communications and Networks                     *
 *                                                                             *
 * File:         UserCommand.hpp                                               *
 * Author:       Jan Kalina <xkalinj00>                                        *
 *                                                                             *
 * Created:      12.04.2025                                                    *
 * Last edit:    12.04.2025                                                    *
 *                                                                             *
 * Description:  Header file defining the `UserCommand` class, which           *
 *               represents a parsed user command or message in the IPK25      *
 *               Chat Client.                                                  *
 *                                                                             *
 ******************************************************************************/
/**
 * @file UserCommand.hpp
 * @author Jan Kalina \<xkalinj00>
 * @brief Header file defining the `UserCommand` class for representing user
 *        commands or messages.
 */

#ifndef USER_COMMAND_HPP
#define USER_COMMAND_HPP

#include "Enums/UserCommandTypes.hpp"
#include <string>  // std::string

namespace IPK25ChatClient::Common
{
    /**
     * @class UserCommand
     * @brief Represents a parsed user command or message.
     *
     * @details The `UserCommand` class encapsulates the details of a user
     *          command or message, including its type, the username, secret,
     *          display name, channel ID, and message content.
     */
    class UserCommand final {
    public:
        Enums::UserCommandType mCommandType;  /**< The type of the user command (may be a message instead of a command). */
        std::string mUsername;                /**< The username associated with the command.          */
        std::string mSecret;                  /**< The secret or password for authentication.         */
        std::string mDisplayName;             /**< The display name of the user.                      */
        std::string mChannelId;               /**< The ID of the channel associated with the command. */
        std::string mMessageContent;          /**< The content of the message, if applicable.         */

        /**
         * @brief Equality operator for UserCommand class.
         *
         * @details This operator compares two UserCommand objects for
         *          equality. It is automatically generated by the compiler
         *          and compares all member variables.
         *
         * @param other The other UserCommand object to compare with.
         * @return `true` if all member variables are equal, `false` otherwise.
         */
        bool operator==(const UserCommand &other) const = default;
    }; // UserCommand
} // IPK25ChatClient::Common

#endif // USER_COMMAND_HPP

/*** end of file UserCommand.hpp ***/
